image: docker:stable

options:
  docker: true

pipelines:
  default:
    - step:
        deployment: Docker Compose Dev
        script:
          - chmod +x docker-compose-dependencies.sh
          - ./docker-compose-dependencies.sh
          - docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
  branches:
    development:
      - step:
          script:
            - docker-compose --env-file ./BookingSystem/.env.dev -f ./BookingSystem/docker-compose.yml -f ./BookingSystem/docker-compose.development.yml -p BookingSystem build
            - docker-compose --env-file ./BookingSystem/.env.dev -f ./BookingSystem/docker-compose.yml -f ./BookingSystem/docker-compose.development.yml -p BookingSystem push