image: docker:stable

options:
  docker: true

pipelines:
  default:
    - step:
        deployment: Test
        script:
          - set -eu
          - apk add --no-cache py-pip bash
          - pip install --no-cache-dir docker-compose
          - docker-compose -v
          - docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
          - 
          - docker-compose run -T client /usr/local/src/test.sh
          - docker-compose down