image: docker:latest

options:
  docker: true

pipelines:
  pull-requests:
    '**':
      - step:
          script:
            - cd ./BookingSystem/BookingSystem.Application.Test
            - dotnet --version
            - dotnet restore
            - dotnet build
            - dotnet test
  branches:
    development:
      - step:
          image: docker:stable
          deployment: Development
          script:
            - chmod +x docker-compose-dependencies.sh
            - ./docker-compose-dependencies.sh
            - docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
            - docker-compose --env-file ./BookingSystem/.env.dev -f ./BookingSystem/docker-compose.yml -f ./BookingSystem/docker-compose.development.yml -p BookingSystem build
            - docker-compose --env-file ./BookingSystem/.env.dev -f ./BookingSystem/docker-compose.yml -f ./BookingSystem/docker-compose.development.yml -p BookingSystem push