version: '3.4'

services:
  bookingsystem.webapi:
    image: ${DOCKER_REGISTRY-}bookingsystemwebapi${DOCKER_ENV}
    build:
      context: .
      dockerfile: BookingSystem.WebApi/Dockerfile
    depends_on: [bookingsystem.identity]
    container_name: bookingsystem.webapi
  bookingsystem.identity:
    image: ${DOCKER_REGISTRY-}bookingsystemidentity${DOCKER_ENV}
    build:
      context: .
      dockerfile: BookingSystem.Identity/Dockerfile
    container_name: bookingsystem.identity
