version: '3.4'

services:
  bookingsystem.webapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=123456
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    ports:
      - "80:80"
      - "443:443"
  bookingsystem.identity:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=123456
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    ports:
      - "80:80"
      - "443:443"
  bookingsystemdb:
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Ae8xWeo4!*EtR7"
    ports:
      - "1433:1433"
    volumes:
      - bookingsystem-sqldata:/var/opt/mssql

volumes:
  bookingsystem-sqldata: