version: '3.4'

networks:
  bookingsystemnetwork:

services:
  bookingsystem.webapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Local
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=123456
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    ports:
      - "5000:80"
      - "5100:443"
    volumes:
      - ~/.aspnet/https:/https:ro
    networks:
      - bookingsystemnetwork
  bookingsystem.identity:
    environment:
      - ASPNETCORE_ENVIRONMENT=Local
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=123456
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    ports:
      - "5001:80"
      - "5101:443"
    volumes:
      - ~/.aspnet/https:/https:ro
    networks:
      - bookingsystemnetwork