version: '3.4'

services:
  bookingsystem.webapi:
    image: ${DOCKER_REGISTRY-}bookingsystemwebapi
    build:
      context: .
      dockerfile: BookingSystem.WebApi/Dockerfile
    depends_on: [bookingsystem.identity]
    container_name: bookingsystem.webapi
    platform: linux
  bookingsystem.identity:
    image: ${DOCKER_REGISTRY-}bookingsystemidentity
    build:
      context: .
      dockerfile: BookingSystem.Identity/Dockerfile
    container_name: bookingsystem.identity
    platform: linux
